### ISSUE TITLE
Add installation guide to README.md

### ISSUE THREAD

**Issue by yairf-s1** [xiamaz/YabaiIndicator#1]
I can't add labels but this should probably be 'documentation'

**Comment by xiamaz** [comment]
What do you mean by labels?

**Comment by yairf-s1** [comment]
awesome  
just a question, why does it say it requires sip disabled? it seems to work for me with sip enabled  
except for one feature which is clicking the spaces (yabai also can't switch spaces without sip disabled so i assume its the same limitation)

**Comment by xiamaz** [comment]
Yes, SIP is required for switching spaces, other features should work, but I don't have a machine with SIP to test. Good to hear that it works!
