### ISSUE TITLE
Preferences window does not open

### ISSUE THREAD

**Issue by manugildev** [xiamaz/YabaiIndicator#10]
Just installed version 0.3.3 and clicking on the "Preferences" item in the menu does not open nothing.

By looking at the code it seems the dialog being opened does not exist.

https://github.com/xiamaz/YabaiIndicator/blob/1efc8aea1be71884f59434e70a2149f0d9cfeba1/YabaiIndicator/YabaiAppDelegate.swift#L127

**Comment by hyan46** [comment]
I have exactly the same problem.

**Comment by xiamaz** [comment]
Should be fixed in `0.3.4`.
