### ISSUE TITLE
Indicator doesn't update instantly after yabai actions relate to space

### ISSUE THREAD

**Issue by ghost** [xiamaz/YabaiIndicator#13]
when using the following yabai action to create or destroy space and change focus, the indicator won't update instantly, for example  when I use "alt-n" to create new space and move focused window to it the indicator will act like this until the next yabai action
<img width="187" alt="Screen Shot 2023-03-30 at 7 37 15 PM" src="https://user-images.githubusercontent.com/65021537/228824657-b57dad1b-3355-4de7-8404-dbecba37f62a.png">
and when I destroy a space and move focus to the previous space, the indicator won't update until the next yabai action.
my skhdrc file relates to the action
```
# create desktop, move window, follow focus
alt - n : yabai -m space --create && \
                  index="$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index')" && \
                  yabai -m window --space "${index}" && \
                  yabai -m space --focus "${index}"

# destroy desktop
meh - x : yabai -m space --focus prev && yabai -m space next --destroy
```
the ending of my yabairc file
```
# signal for yabai indicator
yabai -m signal --add event=mission_control_exit action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=display_added action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=display_removed action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_created action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_destroyed action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_focused action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_moved action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_resized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_minimized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_deminimized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
echo "refresh" | nc -U /tmp/yabai-indicator.socket

echo "yabai configuration loaded..."

```

**Comment by xiamaz** [comment]
Hey, I believe the current events in my README does not seem to cover space creation & destruction. Since you are doing this via your own custom commands the most straightforward way to force a refresh is by just adding `echo "refresh" | nc -U /tmp/yabai-indicator.socket` at the end of your commands.

Currently there is not really a good way to catch everything happening with yabai in the indicator.
