### ISSUE TITLE
yabai v5.0.2 support

### ISSUE THREAD

**Issue by mbalazy** [xiamaz/YabaiIndicator#8]
Are you going to support version 5.0.2 of yabai?
I installed the package, ran it and nothing shows up in the bar.

**Comment by mbalazy** [comment]
Sorry, I just realised that I don't have space to display an additional menulet.
I installed bartender, hide some elements and not it's all working good.

I have one question now, is there any way that I can perform 'refresh' on the spaces indicator? 
For eg. when i perform  `yabai -m space --move prev` I still can see a previous state of spaces in indicator, but when I just move to next space - all is good.

**Comment by xiamaz** [comment]
Thanks for the update. I did now test this with the `5.0.2` and everything seems to be mostly in working order.

For your issue the easiest way is probably to append the following command after your space moving command:

```
echo "refresh" | nc -U /tmp/yabai-indicator.socket
```

This will refresh the indicator manually and is also required for certain other events where the indicator might not update automatically (see README).
